name: OCaml-CI
on: [push, pull_request]
jobs:
  macos_and_windows:
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest]
        ocaml-version: [4.11.1]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pinning Package
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
    - name: Packages
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
    - name: Dependencies
      run: opam install -t -y . --deps-only
    - name: Building, Installing and Testing
      run: opam exec -- dune build @install @runtest
  debian_10_buster:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:4f908274fd1f29675761c0aee33a2e487b3cfb3394023458ce461339236f7d19
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  alpine_3_12:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:8b2b0b0680a6a3967adc85eb9b35fa1c2053ffe61fedc693a86e40e985945249
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  ubuntu_20_04:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:006f06a95502bdd66e07a739bb39acf5ba77276b8bc6acf8ae25bd7de5205cb7
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  ubuntu_18_04:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:5de979c403ddf16498f636b3887c62fb6ce66a191ecf5d64d7819eaa2a80d776
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  opensuse_15_2_leap:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:8e4cdf499f8c35e3278edf02d02aa8a5c33a79d6680cdf8cbfcd0369eefcdfdd
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  centos_8:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:1cdf24f875d20d0367cb7c8282487470c7728265224002a339cdbe4440fe8a60
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  fedora_32:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:896b2c51e375f84369c467f04709b7ce5329bcd6e79403d25cc97f3172b97100
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e bf94421703ae6d95113e5b24890f304701e47b78
        || git fetch origin master) && git reset -q --hard bf94421703ae6d95113e5b24890f304701e47b78
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn opam-github-workflow.dev './' && opam pin add -yn github-workflow.dev
        './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt opam-github-workflow.dev github-workflow.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
